service: james-c5-serverless-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment
    

functions:
  firstfuntion:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /james
          method: get
      
  secondfunction:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /james
          method: post
      - sqs:
          arn:
            Fn::GetAtt:
              - JamesQueue
              - Arn

resources:
  Resources:
    JamesQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "James-queue"


plugins:
  - serverless-offline
