service: james-c5-serverless-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment
    

functions:
  firstfuntion:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /james
          method: get
      - sqs:
          arn:aws:sqs:us-east-1:255945442255:James-sqs

  secondfunction:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /james
          method: post

plugins:
  - serverless-offline
