service: james-c5-serverless-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  firstfuntion:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /james
          method: get

  secondfunction:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /james
          method: post

plugins:
  - serverless-offline
