service: james-c5-serverless-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  jamesapi:
    handler: index.james
    events:
      - httpApi:
          path: /
          method: get

  pranatapost:
    handler: index.jamespost
    events:
      - httpApi:
          path: /james
          method: post

plugins:
  - serverless-offline
